### ISSUE TITLE
I'm really confused on how to use this

### ISSUE THREAD

**Issue by eorroe** [Raathigesh/Atmo#28]
Could you make a video on how this is used?

**Comment by Raathigesh** [comment]
1. Install the `atmo` globally with `npm install atmo -g`
2. Open command prompt and type `atmo` and you will get two URLs.
     - First URL ([http://localhost:3333](http://localhost:3333)) is the UI where you can create the endpoints.
     - Click the 'Deploy' button in the UI to deploy the changes you have made.
     - Use the second URL ([http://localhost:3334](http://localhost:3334)) to access the APIs you have created.

Let me know weather still it's unclear. I will try to make a getting started video.

**Comment by eorroe** [comment]
Just tried it this is really interesting. This would go so ahead of what you probably have in mind, but just wondering how hard that would be to implement. What if I did `atmo app.js` and it was able to read every route implemented via expressjs and it outputed it to the atmo dashboard (again just wondering if you'd be interested in playing with something like that)

**Comment by Raathigesh** [comment]
Glad you managed to get it working. 

It's an interesting idea to load an already written app but the problem would be Atmo curretntly returns JSON on routes but in an exising express application there would be custom implementation (JavaScript Code), So it could be tricky to load them in a UI. 

What kind of advantage a feature like that would bring ?

**Comment by eorroe** [comment]
Right now I wouldn't use this but when it comes to building a rest api for hackathons this could be useful.

The advantage may be to visually see each endpoint. Not sure how much of an advantage that would be. (I wouldn't focus on that right now, just leave this issue open on that or I can create another issue for that and close this one?? then when you get more users someone may vote for this)

**Comment by Raathigesh** [comment]
[Swagger UI ](http://swagger.io/swagger-ui/) would be an ideal way if you want to visualize endpoints. I'm closing this for the time being. Let's reopen if this idea has some potential value.
