### ISSUE TITLE
Open the dashboard automatically after running the atmo command

### ISSUE THREAD

**Issue by eorroe** [Raathigesh/Atmo#30]
Its a simple `start http://localhost:3333` in batch

**Comment by Raathigesh** [comment]
Would you like to add these and send a PR ? If we are doing it, it should be cross-platform.

**Comment by eorroe** [comment]
You're not using a `bat` or `bash` file anywhere, are you using the node `readline` api, if so can you show me which file?

**Comment by Raathigesh** [comment]
If you want to use any node api, you should be able to do it in the [server](https://github.com/Raathigesh/Atmo/blob/master/src/server/server.js).

**Comment by Raathigesh** [comment]
We could use the following modules to open the URL.

- https://www.npmjs.com/package/openurl
- https://www.npmjs.com/package/open

**Comment by eorroe** [comment]
Yea I saw those, was trying to look for one that node provides already, I'm sure its not much code, at least it gets rid of a dependency. So just looked at the code of `openurl` as I was writing this and you don't need much:
```js
let spawn = require('child_process').spawn;
var command;

switch(process.platform) {
    case 'darwin':
        command = 'open';
        break;
    case 'win32':
        command = 'explorer.exe';
        break;
    case 'linux':
        command = 'xdg-open';
        break;
    default:
        throw new Error('Unsupported platform: ' + process.platform);
}
spawn(command, ['http://localhost:3333']); // this opens it, THAT'S IT!!
```

**Comment by eorroe** [comment]
I hate switch statements so I wrather use an Object literal:
```js
let spawn = require('child_process').spawn;

let platforms = {
  'darwin': 'open',
  'win32': 'explorer.exe',
  'linux': 'xdg-open'
}

spawn(platforms[process.platform], ['http://localhost:3333']); // this opens it, THAT'S IT!!
```

**Comment by eorroe** [comment]
Btw you should make this optional, meaning run this if I do something like `atmo -o` o standing for open

**Comment by Raathigesh** [comment]
Users can't do anything without the mission control UI. I think it would make more sense to open the UI by default when Atmo is started. Why do you think we should keep the option under an optional flag ?

**Comment by eorroe** [comment]
You're right, I can't remember why I thought to have that option it was 2am at that time. Idk what I was thinking, but yea go ahead and do that thanks.

**Comment by Raathigesh** [comment]
Added to the 1.0 roadmap as an enhancement. https://github.com/Raathigesh/Atmo/issues/34
