### ISSUE TITLE
Get rid of the Star Button?

### ISSUE THREAD

**Issue by eorroe** [Raathigesh/Atmo#31]
The star button on the dashboard, is a bit distracting. Especially since it doesn't match the current star count. Mine still at 30, perhaps it should match the current star and say "unstar" if I already starred it. Or just remove it.

**Comment by Raathigesh** [comment]
I also noticed that it's not displaying the correct count! I want a way for the users to easily locate the GitHub repo to file issues or look at the docs. Let's change the button to a smaller GitHub button which links to the repo.

**Comment by eorroe** [comment]
Sounds good

**Comment by Raathigesh** [comment]
Fixed in release [v0.12.0](https://github.com/Raathigesh/Atmo/releases/tag/v0.12.0)
