### ISSUE TITLE
How to implement Mutations of graphql and custom mock data for:

### ISSUE THREAD

**Issue by Danjavia** [Raathigesh/atmo#35]
- Date
- String
- Number
- Int without negative value

test mutations?.

Many thanks

**Comment by Raathigesh** [comment]
Right now both mutations and custom mocks are not supported. I couldn't invest time on GraphQL module for some time. I will look into this and get back.

**Comment by Raathigesh** [comment]
Closing this for now. The plans for the next version of Atmo (https://github.com/Raathigesh/atmo/issues/34) is slightly different. I'm not planning to focus on GraphQL in the initial release since there are much feature rich tools out there. Your comments would be appreciated!
