### ISSUE TITLE
error

### ISSUE THREAD

**Issue by GlauberF** [Raathigesh/Atmo#36]
![atmo](https://cloud.githubusercontent.com/assets/11314585/20108429/36ad82a2-a5c3-11e6-9b73-98ea9fac952f.png)

----

![atmo1](https://cloud.githubusercontent.com/assets/11314585/20108554/8ab9c298-a5c3-11e6-854f-90111bc0309e.png)

**Comment by Raathigesh** [comment]
Did you click the `deploy` button? Can you share a screenshot for reference?

**Comment by GlauberF** [comment]
Yes, I click the deploy button, it opens a new tab, but generates the error

![erro atmo](https://cloud.githubusercontent.com/assets/11314585/20139080/75a40ffa-a66b-11e6-96f0-a510879fc632.png)

**Comment by Raathigesh** [comment]
Would you be able to send the spec.json file? You could get the file by clicking `export` button.

**Comment by GlauberF** [comment]
Hello, this is my spec.json file, just convert to txt, to upload here to github

[spec.txt](https://github.com/Raathigesh/Atmo/files/583119/spec.txt)

**Comment by Raathigesh** [comment]
In the `/proxy` endpoint, you did not specify the host URL. Either remove the `/proxy` endpoint or provide the host url.

![image](https://cloud.githubusercontent.com/assets/3108160/20174827/d0b0651a-a765-11e6-8bde-cc810d6389c2.png)

**Comment by GlauberF** [comment]
ok, test it
