### ISSUE TITLE
can't change CP Port

### ISSUE THREAD

**Issue by Chathula** [Raathigesh/Atmo#37]
Is there a way to change the port of Atmo mission control? i think it is a necessary thing for the users.

**Comment by Raathigesh** [comment]
I agree but unfortunately there is no direct parameter to specify the mission control port. I will add an option soon.

But if you set the `process.env.PORT` variable, [Atmo will use that.](https://github.com/Raathigesh/Atmo/blob/master/src/server/server.js#L32)

In a windows machine, you could set the port by executing `set port=5555` in the command prompt and then executing  `atmo` in the same command prompt. Now Atmo will use 5555 as the port.

[More info on setting environment variable in other platforms.](http://stackoverflow.com/questions/13333221/how-to-change-value-of-process-env-port-in-node-js)

**Comment by Chathula** [comment]
Thank you for info!!!

**Comment by Raathigesh** [comment]
Added this to roadmap #34
