### ISSUE TITLE
response dealy [enahcment] 

### ISSUE THREAD

**Issue by pantchox** [Raathigesh/atmo#38]
hi! love the project!
small suggestion, maybe for each request can we set a delay, to test client side loaders and such.
so for each request you can have "ms" delays, should be a super cool addon.

Thanks!

**Comment by Raathigesh** [comment]
I'm glad that you find the project useful. 

Luckily there is an easy way to achieve this. Atmo allows you to write custom JavaScript where you can access the request and response object of express js (Atmo uses express js under the hood) through `req` and `res` variables .

Just select the `JavaScript` option from the dropdown and use setTimeout() to mimic the delay as shown below and use the `res.send()` method to send your response.

A bit more detail [here](https://github.com/Raathigesh/Atmo/blob/master/docs/ConditionalResponseWithHttpEndpoint.md).

![image](https://cloud.githubusercontent.com/assets/3108160/20739875/98685a30-b6e4-11e6-9cf1-ddbfbd9445da.png)

**Comment by pantchox** [comment]
very interesting!
but what if i use json-server? :)
thanks for the quick reply!

**Comment by Raathigesh** [comment]
In that case, you can't :)  I will try to add a delay when I could find some time.

**Comment by Raathigesh** [comment]
https://github.com/Raathigesh/atmo/issues/34
