### ISSUE TITLE
Bug in server when editing "Response Headers"

### ISSUE THREAD

**Issue by pantchox** [Raathigesh/Atmo#43]
When creating a new http endpoint, the default "Response Headers" first row is "Access-Control-Allow-Origin: *" which is great it allows us CORS.
but if i click on it to edit it a new headers row is added under it.
If i don't add new header and leave the new row fields empty, clicking "Deploy" and "Save" , closing and reloading atmo causes the endpoint to return "404" error.
in my case the endpoint was a "200 OK" and "POST"

Thanks.

**Comment by Raathigesh** [comment]
Unfortunately, I couldn't reproduce the issue.

**Comment by pantchox** [comment]
i will try to write a more specific reproduce to this bug tommrow, there is def' a bug.
thanks!

**Comment by pantchox** [comment]
i could not reproduce this bug.
