### ISSUE TITLE
Generate Project http endpoints with response type javascript doesnt work

### ISSUE THREAD

**Issue by pantchox** [Raathigesh/atmo#44]
Hi, 
I noticed writing javascript code in the response of http endpoint when generating project and running the project, there is an error.

i think the part of taking the javascript code and attaching it to the generated project "server.js" file is not working.

:(

**Comment by Raathigesh** [comment]
Currently, the [generator ](https://github.com/Raathigesh/AtmoExpressES5Generator) doesn't support JavaScript snippets. Will issue a fix.

**Comment by pantchox** [comment]
see pull request.

**Comment by Raathigesh** [comment]
Thank you. Released [v0.14.1](https://github.com/Raathigesh/Atmo/releases/tag/0.14.1)
