### ISSUE TITLE
Cannot run atmo after install -g 

### ISSUE THREAD

**Issue by siriwatknp** [Raathigesh/atmo#45]
After I type npm install -g atmo and then run atmo from terminal, I got this error.
`env: node\r: No such file or directory`

First I thought it's because my npm folder is not correct, however when I rollback to use atmo version 0.14.0, it worked. My friend also found this problem with 0.14.1

**Comment by Raathigesh** [comment]
Could you please confirm whether this is happening in a Mac ?

**Comment by siriwatknp** [comment]
Yes

**Comment by Raathigesh** [comment]
I do development on a windows machine and this is to do with incorrect line ending in the entry script of the module. I will fix this real soon. Until then could you please continue using 0.14.1 or is there anything else blocking from doing so ?

**Comment by siriwatknp** [comment]
Like I said, now I am using 0.14.0 because 0.14.1 cannot run.

**Comment by Raathigesh** [comment]
Sorry, I was not able to reply here after releasing 0.14.2. Closing this for now. Please re-open if you still have difficulty with atmo.
