### ISSUE TITLE
Unable to deploy to server

### ISSUE THREAD

**Issue by upgundecha** [Raathigesh/atmo#47]
My Setup -

Machine A - Atmo Server (Client & Server)
Machine B - Laptop machine from where I am defining a JSON prototype and deploying to Machine A

When I try to create and deploy a new prototype from my machine to the Atmo server (Machine A), I see a message 'Deploying...' but nothing happens. The JSON prototype is not getting deployed. Do I need to make any additional configs?

It would be great to have Gitter channel for Atmo project.

**Comment by Raathigesh** [comment]
It should work without any additional configuration. Do you see any console errors? Does the client having trouble establishing the socket connection? 

I agree that gitter would be useful. Just created one https://gitter.im/atmo-connect!

**Comment by upgundecha** [comment]
Thanks @Raathigesh!  It was trouble with socket and pointed to localhost. 

Big thanks for Gitter 👍
