### ISSUE TITLE
How to implement two way SSL (mutual SSL Authentication) with the Atmo

### ISSUE THREAD

**Issue by RohitShinkar** [Raathigesh/atmo#49]
@Raathigesh 
Hi, 
I've a scenario which needs a mutual SSL authentication to validate the response.

Is there any way we can implement this in Atmo ?

**Comment by Raathigesh** [comment]
Unfortunately you can't do it now. But it's will be added soon with the up-coming re-write - https://github.com/Raathigesh/atmo/issues/34
