### ISSUE TITLE
Do you have a plan to generate sample data or define a schema?

### ISSUE THREAD

**Issue by iamgoangle** [Raathigesh/atmo#51]
Do you have a plan to option to create schema and auto generate sample data base on user-define schema?

**Comment by Raathigesh** [comment]
That's an interesting idea! Right now I'm not planning to work on features! Trying to explore some other areas with other projects! If you are interested in implementing it, please go ahead and send a PR! I would be happy to discuss the details of the approach!

**Comment by Raathigesh** [comment]
Closing for now. Please re-open if required.
