### ISSUE TITLE
Can I change JSON Server Endpoint?

### ISSUE THREAD

**Issue by JayCoPurcell** [Raathigesh/atmo#54]
When I create new JSON Server Endpoint I can't change '/api' to '/myttt'. Is there a way to change this?

**Comment by Raathigesh** [comment]
Are you using the electron app or the CLI?

**Comment by JayCoPurcell** [comment]
CLI

**Comment by Raathigesh** [comment]
You should be able to change the URL by changing it here.
![image](https://user-images.githubusercontent.com/3108160/34101526-163039d2-e43a-11e7-8768-392bac4d6e09.png)

**Comment by JayCoPurcell** [comment]
I see it, but it doesn't work. I've changed '/api' to '/myttt' and then I deployed, but when I make a response to '/myttt' server send's 404:
<pre>Cannot GET /mytttt</pre>

**Comment by Raathigesh** [comment]
Then it seems like a bug, unfortunately!

**Comment by JayCoPurcell** [comment]
Can you fix it?

**Comment by Raathigesh** [comment]
I don't maintain the CLI version of Atmo anymore and the electron app version does not support JSON server endpoints. Sorry!
